services:
  - type: web
    name: nse-screener-backend
    env: node
    region: singapore
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
